/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) long int csv2xlsx(char* pszCsv, char* pszOptions);
extern __declspec(dllexport) long int csv2xlsx_with_style(char* pszCsv, char* pszOptions, char* pszStyles);
extern __declspec(dllexport) uintptr_t xlsx_load_file(char* path);
extern __declspec(dllexport) void xlsx_close_file(uintptr_t handle);
extern __declspec(dllexport) int xlsx_get_sheet_count(uintptr_t handle);
extern __declspec(dllexport) char* xlsx_get_sheet_name(uintptr_t handle, int sheetIndex);
extern __declspec(dllexport) int xlsx_get_row_count(uintptr_t handle, int sheetIndex);
extern __declspec(dllexport) int xlsx_get_col_count(uintptr_t handle, int sheetIndex, int row);
extern __declspec(dllexport) char* xlsx_get_cell_value(uintptr_t handle, int sheetIndex, int row, int col);
extern __declspec(dllexport) void xlsx_free_string(char* str);
extern __declspec(dllexport) uintptr_t xlsx_create_file();
extern __declspec(dllexport) int xlsx_add_sheet(uintptr_t handle, char* sheetName);
extern __declspec(dllexport) void xlsx_set_cell_value(uintptr_t handle, int sheetIndex, int row, int col, char* value);
extern __declspec(dllexport) int xlsx_save_file(uintptr_t handle, char* filename);

#ifdef __cplusplus
}
#endif
